---
apiVersion: v1
kind: Namespace
metadata:
  name: datastore
  labels:
    name: datastore

---
apiVersion: v1
kind: Pod

metadata:
  namespace: datastore
  name: datastore-mongo
  annotations:
  labels:
    app: datastore-mongo
spec:
  containers:
  - name: mongo
    image: mongo
    ports:
      - containerPort: 27017

---

kind: Service
apiVersion: v1
metadata:
  name: mongodb-service
  namespace: datastore
spec:
  selector:
    app: datastore-mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  datastore-deployment
  namespace: datastore
spec:
  selector:
    matchLabels:
      app: datastore
  replicas: 1
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
      - name: datastore
        image: hmharsh3/myapp:11 
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: datastore-service
  namespace: datastore
  labels:
    app: service-datastore
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 #// container port
    nodePort: 30085
  type: NodePort
  selector:
    app: datastore


---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datastore-hpa
  namespace: datastore
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: datastore-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
