---
apiVersion: v1
kind: Namespace
metadata:
  name: datastoreapp
  labels:
    name: datastoreapp

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongoapp-pv
  namespace: datastoreapp
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongostoreapp-pvc
  namespace: datastoreapp
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 90Mi


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-mongo
  namespace: datastoreapp
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
          - containerPort: 27017
        volumeMounts:
        - mountPath: "/data/db"
          name: datastore-volume-mount
      volumes:
      - name: datastore-volume-mount
        persistentVolumeClaim:
          claimName: mongostoreapp-pvc


---

kind: Service
apiVersion: v1
metadata:
  name: mongodb-service
  namespace: datastoreapp
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  datastore-deployment
  namespace: datastoreapp
spec:
  selector:
    matchLabels:
      app: datastore
  replicas: 1
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
      - name: datastore
        image: hmharsh3/myapp:11
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: datastore-service
  namespace: datastoreapp
  labels:
    app: service-datastore
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 #// container port
    nodePort: 30085
  type: NodePort
  selector:
    app: datastore


---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datastore-hpa
  namespace: datastoreapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: datastore-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
