global:
  scrape_interval: 5s
  evaluation_interval: 5s
  query_log_file: /etc/prometheus/query.log
rule_files:
- rules/*_rules.yml

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['172.31.27.52:9100', '172.31.24.80:9100', '172.31.17.88:9100']



  - job_name: 'my-node-app'
    honor_labels: true
    static_configs:
    - targets: ['172.31.27.52:30081/metrics', '172.31.27.52:30081/swagger-stats/metrics']

